### ISSUE TITLE
I ran Python 3.7 with an error

### ISSUE THREAD

**Issue by ghost** [Bearle/django-private-chat#43] opened 2019-09-05 06:14 UTC
* django-private-chat version:
* Django version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
If it's too long, please use http://pastebin.com
```
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax

**Comment by saemideluxe** [comment] 2019-09-11 09:32
This is a duplicate of #41

**Comment by morenoh149** [comment] 2020-04-30 17:42
this was fixed. Please close.

**Comment by delneg** [comment] 2020-05-03 13:30
Check 0.3.0

**Closed as completed by delneg** 2020-05-03 13:30 UTC
